### ISSUE TITLE
Address failing Java compatibility tests

### ISSUE THREAD

**Issue by aiven-anton** [Aiven-Open/kio#100]
The Java tester is currently disabled for a few entities that aren't passing, see link to exclusion. We should address these issues and make sure the test is enabled for all entities.

https://github.com/Aiven-Open/kio/blob/04f631757bcdd754b0dcafc7fc53d2416ce254f0/codegen/generate_tests.py#L119

---

### Entities with records

- https://github.com/Aiven-Open/kio/pull/176

Records support has been intentionally deferred until most other things is working as expected. Records are not defined as a schema, and has separate encoding, so it requires some more manual parsing and serializing implementations. There's also the possibility that we don't want to eagerly parse records, but rather build some lazy functionality to allow good performance when used in proxy functionality that doesn't have the need to inspect records.

- [ ] `ProduceRequest`
- [ ] `FetchResponse`
- [ ] `FetchSnapshotResponse`

---

### Tagged fields issue

- [x] `FetchRequest` #102

Should not output tagged field if its value equals to default. The tagged field in this case is a nested entity which is why this is behaving differently than other tagged fields. To deal with this efficiently we need to avoid instantiating entities at serialization-time, therefore just like with primitives, the default should be defined in the model. The `replica_state` field needs to change into:

```python
replica_state: ReplicaState = field(
    metadata={"tag": 1},
    default=ReplicaState(),
)
```

This needs some fancy detection, as it's only possible when all fields of the nested model in turn have defaults (this is why only a single model in the entire protocol schema excersises this behavior).

---

### Nullable bug

Nullable `assignment` field. This is a bug in the code generation, the field should be None-able and have `None` as default.

- [x] `ConsumerGroupHeartbeatResponse` #101.

**Comment by aiven-anton** [comment]
The issue with `ConsumerGroupHeartbeatResponse` is not super straightforward, I've opened an issue on the Kafka tracker to inquire how such fields represent null and how that should be disambiguated from tagged fields etc.

Cross-referencing:

- https://github.com/apache/kafka/pull/14124#issuecomment-1820758554
- https://issues.apache.org/jira/browse/KAFKA-15869

**Comment by antonagestam** [comment]
Random note: a possible way to implement Hypothesis strategy for record batches.

- Bring aiokafka as test dependency (better maintained than kafka-python, and vendors everything we need).
- Teach Hypothesis how to use the MemoryRecords and Record entities to ... build entities.
- Introduce _some_ type for records fields. Might be sufficient with a NewType, might not.
- Register the Hypothesis strategy for that type.
