### ISSUE TITLE
Provide mapping between requests and response

### ISSUE THREAD

**Issue by aiven-anton** [Aiven-Open/kio#115]
The library should provide some way to map between request and response, such that given a request model, it's possible to retrieve its corresponding response model.

One way would be to add a field to requests, but that would introduce a runtime dependency between request and response modules, which seems like a good idea to avoid.

Another way is to provide a function that traverses the module tree, this seems easy to implement but a bit ugly ...

**Comment by antonagestam** [comment]
I've been tinkering a bit with a use case that needs this, for dynamically loading the right model based on incoming requests.

What I'm landing in would be the optimal design here, is code generation to produce a `kio.schema.index` module, containing a mapping from `(api_key, api_version)` to modules and names. The signature of the loader function would like this.


```python
def load_response_schema(api_key: i16, version: i16) -> type[ResponsePayload]: ...
def load_request_schema(api_key: i16, version: i16) -> type[RequestPayload]: ...
# Data and header schemas do not have API keys, so would be exposed by name instead.
def load_header_schema(name: str, version: i16) -> type[Entity]: ...
def load_data_schema(name: str, version: i16) -> type[Entity]: ...
```

In addition to loading the main schema type, it's likely also sensible to expose a mechanism for loading the respective modules:

```python
def load_payload_module(api_key: i16, version: i16) -> type[ModuleType]: ...
def load_entity_module(name: str, version: i16, entity_type: EntityType) -> type[ModuleType]: ...
```

**Comment by antonagestam** [comment]
For reference, I did an experiment with dynamically importing the full schema (all entity modules): this takes between 2-3 seconds.

https://gist.github.com/antonagestam/86f96f3dccee8c8ff7711f9647c5783a

**Comment by antonagestam** [comment]
Draft implementation here: https://github.com/Aiven-Open/kio/pull/150/. Missing code generation and tests.
